### ISSUE TITLE
Sinon 3.3.0 dependency has a major security vulnerability

### ISSUE THREAD

**Issue by Syzygy24** [csantero/ember-sinon#134]
ember-sinon@1.0.1 > sinon@3.3.0 > build@0.1.4 > uglify-js@1.3 -- https://nodesecurity.io/advisories/39

I believe sinon 3.3.0 is getting pulled in here https://github.com/csantero/ember-sinon/blob/master/yarn.lock#L5500, but package.json has sinon v4. Not sure why that is.

This seems to be fixed in higher sinon version numbers. I'm not sure what the process is like for updating the sinon version in this repo.

**Comment by elwayman02** [comment]
The yarn.lock wasn't updated by greenkeeper, it needs an update.

**Comment by Syzygy24** [comment]
made a pr here: https://github.com/csantero/ember-sinon/pull/135. Ember-beta build is failing right now, but that's 3.1 now I believe. There might be some more significant work required to make that pass.
