### ISSUE TITLE
Added sinon-chai?

### ISSUE THREAD

**Issue by mmahalwy** [csantero/ember-sinon#18]
Can this be included?

**Comment by csantero** [comment]
@mmahalwy I would be amenable to a PR that adds this in the same way we add sinon-qunit.

**Comment by mmahalwy** [comment]
Ill take a look into adding it :)

**Comment by elwayman02** [comment]
@csantero @mmahalwy I would recommend creating a separate addon `ember-sinon-chai` much in the same fashion as [`ember-sinon-qunit`](https://github.com/elwayman02/ember-sinon-qunit)

**Comment by csantero** [comment]
@elwayman02 Agreed, gonna go ahead and close this in favor of a separate addon.
