### ISSUE TITLE
Deprecate in favor of ember-auto-import?

### ISSUE THREAD

**Issue by elwayman02** [csantero/ember-sinon#181]
Can this addon now be deprecated, since ember-auto-import should let sinon be imported as a package? Is there any reason apps on the latest supported Ember versions wouldn't be able to switch to that approach?

**Comment by csantero** [comment]
@elwayman02 Yeah I had this same thought recently. This addon doesn't do anything that ember-auto-import (and eventually embroider) can't do better.

**Comment by bendemboski** [comment]
FWIW I've been consuming `sinon` via `ember-auto-import` for quite a while now, and it works seamlessly (and puts me in full control of my `sinon` version!). So I agree that it can be deprecated.

**Comment by elwayman02** [comment]
After speaking with @scalvert, we decided to wait on removing `ember-sinon-qunit`'s dependency on `ember-sinon` until Embroider is more stable. I'm ambivalent on marking this package as deprecated until then, but I agree that most people can probably migrate to `ember-auto-import` today.

**Comment by elwayman02** [comment]
@csantero @scalvert we've landed a new major release of `ember-sinon-qunit` which [switches to `ember-auto-import` and `webpack`](https://github.com/elwayman02/ember-sinon-qunit/pull/727), and I believe the current world of e-a-i v2 makes it possible for any other consumers to do the same. I'd suggest we move forward with fully marking this package as deprecated at this point. Thoughts?
