### ISSUE TITLE
Could not find module ./sinon/util/core

### ISSUE THREAD

**Issue by ballPointPenguin** [csantero/ember-sinon#19]
ember-sinon 0.2.1
sinonjs: 1.14.1

ember-cli 1.13.1
node: 2.4.0
npm 2.12.1

problem occurs when I state
```
import sinon from 'sinon';
```
at the top of a unit test

possibly related to:
https://github.com/cjohansen/Sinon.JS/issues/541
where cjohansen says that sinon does not support bower.

**Comment by kadamwhite** [comment]
I'm running into this as well; what was the resolution?

**Comment by csantero** [comment]
@kadamwhite are you on version 0.5.0? The new version uses npm instead of bower to get sinon.

**Comment by kadamwhite** [comment]
Thanks!
