### ISSUE TITLE
Update Sinon

### ISSUE THREAD

**Issue by lolmaus** [csantero/ember-sinon#23]
This addon is uses a proxy Sinon repo which has an obsolete version.

**Comment by csantero** [comment]
Unfortunately this addon is not compatible with using the source version of sinon as a bower package. It requires a pre-built version, which the [proxy](https://github.com/blittle/sinon.js) provides. I would recommend opening a PR on the proxy repo to add the latest version of sinon. When that repo updates I'll be happy to bump the version ember-sinon is pointing to.

**Comment by lolmaus** [comment]
Done: https://github.com/blittle/sinon.js/releases/tag/v1.17.1

**Comment by csantero** [comment]
Actually I had a brain-fart - there is nothing further to be done in ember-sinon that affects consuming apps. The version in ember-sinon's bower.json is only relevant to this project's tests. You can go ahead and update the version of sinonjs your app is pointing to and it should just work.
