### ISSUE TITLE
Won't work on Ember CLI 1.13.13

### ISSUE THREAD

**Issue by lolmaus** [csantero/ember-sinon#29]
After upgrading my project to Ember CLI 1.13.13, all my tests broke.

I replaced `ember-sinon` with `sinon`, `from 'sinon'` with `from 'npm:sinon'` -- and it works now.

Also, this:

> @lolmaus Looks like it's `ember-sinon` and `ember-cli-blanket` to blame.
> @rwjblue they need to be updated to deal with latest loader.js

**Comment by csantero** [comment]
@lolmaus Are you including sinon from npm? This addon currently requires the `sinonjs` package to be installed via bower for `import sinon from 'sinon';` to work.

**Comment by lolmaus** [comment]
> This addon currently requires the sinonjs package to be installed via bower for import sinon from 'sinon'; to work.

That's what I was initially doing, but it stopped working after upgrading Ember CLI. So I removed it and instead installed Sinon from npm via `ember-browserify`.

**Comment by csantero** [comment]
That's strange. I have apps using Ember CLI 1.13.13 and didn't have to change anything.

I'm also not sure what @rwjblue means by
> they need to be updated to deal with latest loader.js

I'm assuming it's related to [our shim file](https://github.com/csantero/ember-sinon/blob/master/vendor/ember-sinon/shim.js)?

**Comment by rwjblue** [comment]
Was mostly talking about how ember-cli-blanket changes the loader.  See https://github.com/sglanzer/ember-cli-blanket/issues/85.  I haven't debugged this issue directly though, so things could have changed since the last time I helped someone with it.

**Comment by lolmaus** [comment]
I'll close this until someone else chimes in with his report.
