### ISSUE TITLE
400-500 HTTP Response bug in Sinon 1.7.4

### ISSUE THREAD

**Issue by jsmestad** [csantero/ember-sinon#48]
I noticed in the latest `ember-sinon` release the version dependency for sinon.js was updated to `1.7.4` from `1.7.3`. This introduced an error where response body's are not passed back when returning 400...500 HTTP errors.

I am posting here first for folks who hit this issue, but also in case you want to roll out 0.5.2 with the version rolled back to `sinon@1.7.3` - https://github.com/sinonjs/sinon/issues/1057

**Comment by elwayman02** [comment]
Main issue in sinon: https://github.com/sinonjs/sinon/issues/1040

@jsmestad thanks for bringing this to our attention! You can always force the version of `sinon` you want in your project's package.json without having to rollback your `ember-sinon` version, fyi.

**Comment by jsmestad** [comment]
How?

-- 
Justin Smestad

**Comment by elwayman02** [comment]
http://www.codedependant.net/2016/01/26/override-nested-dependencies-npm-3/

**Comment by elwayman02** [comment]
The parent issue in Sinon has been closed, and we've updated to the latest version of Sinon (will go out with the next release). @jsmestad, would love if you could pull our master branch and confirm that the issue is gone for you now!
