### ISSUE TITLE
Cannot find sinon

### ISSUE THREAD

**Issue by DarrenN** [csantero/ember-sinon#7]
* Using ember-cli
* have tried installing with both `ember install:addon ember-sinon` and via npm.
* Bower installs `index.js` in `bower_components/sinon/`

Installing via ember addon:

```shell
$ ember install:addon ember-sinon
version: 0.1.15
Could not find watchman, falling back to NodeWatcher for file system events
Installed packages for tooling via npm.
installing
Installing browser packages via Bower...
  not-cached http://sinonjs.org/releases/sinon-1.12.2.js#*
  resolved http://sinonjs.org/releases/sinon-1.12.2.js#e-tag:2081e4-2c
Installed browser packages via Bower.
Installed addon package.
```
When I try to spin up ember I get:

```shell
Missing bower packages:
Package: sinon
  * Specified: http://sinonjs.org/releases/sinon-1.12.2.js
  * Installed: (not installed)

Run `bower install` to install missing dependencies.
```

When I run `bower install` I get nothing.

When I `ember g ember-sinon` I get:

```shell
version: 0.1.15

Missing bower packages:
Package: sinon
  * Specified: http://sinonjs.org/releases/sinon-1.12.2.js
  * Installed: (not installed)

Run `bower install` to install missing dependencies.
```

Please advise.

**Comment by csantero** [comment]
Have you tried with the latest version of ember-cli? I just made a new app with ember-cli 0.2.1 and added ember-sinon and `ember serve` worked fine.

**Comment by DarrenN** [comment]
I think we can close, I blew away `node_modules` and `bower_components` and re-installed the addon, seems to work now. Unsure what the issue was.

**Comment by csantero** [comment]
Ok, thanks, feel free to reopen if the problem returns.
