### ISSUE TITLE
the example test usage in readme doesn't work  at all

### ISSUE THREAD

**Issue by mgenev** [csantero/ember-sinon#8]
first when you install and try to use sinon, the linter breaks on sinon being undefined, but that's a known issue, i fixed that in the rc file.

But then, when I try the example code from the readme: 

```
test(".runCallback() should run the callback passed", function(assert) {
  var spy = sinon.spy();
  this.subject().runCallback(spy);
  assert.ok(spy.calledOnce, "the callback should be called once");
  assert.ok(spy.calledWith('foo'), "the callback should be passed 'foo' as an argument");
});
```

I get: `'undefined' is not a function (evaluating 'this.subject().runCallback(spy)')` 

EmberCLI is version  0.2.2

**Comment by csantero** [comment]
The intention of that example code is that you're testing an ember component (or something else) that has a `runCallback` method. I'm guessing that what you're testing doesn't have such a method.
