### ISSUE TITLE
Does not work in an Ember Addon

### ISSUE THREAD

**Issue by flyswatter** [csantero/ember-sinon#9]
Ember Addons have their own testing strategy, and this ember-sinon for whatever reason isn't currently compatible with it.

**Comment by christophermlne** [comment]
I just discovered this as well.

**Comment by christophermlne** [comment]
actually nvmd. This works for me. I had to run $ bower install or restart the server. I'm not sure which action fixed it but it was one or the other.

**Comment by csantero** [comment]
Sorry I missed this originally, @flyswatter are you still experiencing this issue or can I mark this as closed?

**Comment by flyswatter** [comment]
I'm not currently working on a sinon-using addon, would take me a bit to verify, but I could totally believe this was my problem, and will reopen if I find my problem persists when I return to it.

**Comment by fsmanuel** [comment]
can we reopen? i'm using ember-cli `0.2.5` in an addon an `ember install ember-sinon` outputs:
`No dependencies installed. Run `npm install` and `bower install` to install missing dependencies.`

when i `npm install --save-dev ember-sinon` and run `ember g ember-sinon` i get:
`No dependencies installed. Run `bower install` to install missing dependencies.` again.

**Comment by fsmanuel** [comment]
with ember-cli `0.2.6` it works. maybe there was something with the setup... no need to reopen.
